
---
- hosts: apache
  sudo: yes
  vars:
   - message: "Welcome ansible Apache"
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: index.html copy
      template: src=index.html.j2 dest=/var/www/html/index.html

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
